config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }
  devise_scope :user do
    get "/users/sign_out" => "users/sessions#destroy"
    post "users/guest_sign_in" => "users/sessions#guest_sign_in"
  end

  root to: "homes#top"
  get "about" => "homes#about"

  resources :users, except: [:new, :index, :destroy] do
    collection do
      get "confirm"
      patch "withdraw"
      get "search"
    end
    resources :requests, only: [:index, :create, :destroy]
    resource :follows, only: [:create, :destroy]
    resources :notifications, only: [:index] do
      patch :read, on: :member
      patch :read_all, on: :collection
    end
  end
  resources :posts, except: [:edit, :index, :show] do
    get "search", on: :collection
    # get '/autocomplete_song/:song', on: :collection, action: :autocomplete_song
    resources :post_comments, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]
  end
  get "users/:user_id/posts/:id", to: "posts#show", as: "post_show"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  after_create_commit :create_notifications

  has_one :notification, as: :subject, dependent: :destroy
  belongs_to :post
  belongs_to :user

  validates :body, presence: true, length: { maximum: 150 }

  def create_notifications
    # セルフコメントは通知を新たに作成しない
    unless self.post.user_id == self.user_id
      Notification.create!(subject: self, user_id: self.post.user_id, action: Notification.actions[:post_comment])
    end
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  before_action :is_matching_login_user, only: [:destroy]

  def create
    @post = Post.find(params[:post_id])
    @post_comments = @post.post_comments.all
    @post_comment = PostComment.new(post_comment_params)
    @post_comment.user_id = current_user.id
    @post_comment.post_id = params[:post_id]
    if @post_comment.save
      flash.now[:success] = "コメントを投稿しました"
    end
  end

  def destroy
    post_comment = PostComment.find(params[:id])
    post_comment.destroy
    flash.now[:secondary] = "コメントを削除しました"
    @post = Post.find(params[:post_id])
    @post_comments = @post.post_comments.all
  end

  private
    def post_comment_params
      params.require(:post_comment).permit(:body)
    end

    def is_matching_login_user
      post_comment = PostComment.find(params[:id])
      unless post_comment.user_id == current_user.id
        redirect_to user_path(current_user.id)
      end
    end
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/views/post_comments/_comments_list.html.erb
<% if @post.post_comments.exists? %>
  <div class="pb-2 pl-3 border-bottom border-primary shadow">コメント　<%= @post_comments.count %></div>
  <div class="mt-4">
    <% @post_comments.each do |comment| %>
    <div class="mb-2 ml-lg-3 d-flex align-items-center" style="font-size: 14px;">
      <%= link_to user_path(comment.user.id), class: "text-decoration-none align-self-start col-lg-3 col-4" do %>
        <%= image_tag comment.user.get_profile_image(40,40), class: "rounded-circle" %>
        <span class="pl-2"><%= comment.user.name %></span>
      <% end %>
      <div class="pl-0 col-8 text-break"><%= comment.body %><span class="pl-3 d-inline-block"><%= comment.created_at.strftime('%Y/%m/%d') %></span>
        <% if comment.user == current_user %>
          <%= link_to "削除", post_post_comment_path(comment.post_id, comment.id),
          method: :delete, remote: true, data: {confirm: "本当に削除しますか？"}, class: "ml-3 d-inline-block" %>
        <% end %>
      </div>
    </div>
    <% end %>
  </div>
<% else %>
  <p class="mt-4 mb-4">コメントはまだありません</p>
<% end %>

app/views/post_comments/_form.html.erb
<%= form_with model: @post_comment, url: post_post_comments_path(post_id: @post.id), local: false do |f| %>
  <div id="flash_message"><%= render 'shared/flash_message' %></div>
  <div id="comments-error"><%= render 'shared/error_messages', model: @post_comment %></div>

  <%= f.text_area :body, id: 'post_comment', class: "form-control" %>
  <%= f.submit 'コメントする', class: "btn btn-primary mt-3" %>
<% end %>

app/views/post_comments/create.js.erb
<!--id="comments_listをrenderで指定した部分テンプレートに更新-->
$("#comments_list").html("<%= j(render 'comments_list') %>");
<!--フォームを送信したあとにフォームの値を空にする-->
$("#post_comment").val('');
$('#flash_message').html("<%= j(render partial: 'shared/flash_message') %>");
$('#comments-error').html("<%= j(render 'shared/error_messages', model: @post_comment) %>");

app/views/post_comments/destroy.js.erb
$("#comments_list").html("<%= j(render 'comments_list') %>");
$('#flash_message').html("<%= j(render 'shared/flash_message') %>");

app/views/post_comments/post_comments.js.erb
<!--id="comments_listをrenderで指定した部分テンプレートに更新-->
$("#comments_list").html("<%= j(render 'post_comments/comments_list' %>");
<!--フォームを送信したあとにフォームの値を空にします-->
$("textarea").val('');