config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }
  devise_scope :user do
    get "/users/sign_out" => "users/sessions#destroy"
    post "users/guest_sign_in" => "users/sessions#guest_sign_in"
  end

  root to: "homes#top"
  get "about" => "homes#about"

  resources :users, except: [:new, :index, :destroy] do
    collection do
      get "confirm"
      patch "withdraw"
      get "search"
    end
    resources :requests, only: [:index, :create, :destroy]
    resource :follows, only: [:create, :destroy]
    resources :notifications, only: [:index] do
      patch :read, on: :member
      patch :read_all, on: :collection
    end
  end
  resources :posts, except: [:edit, :index, :show] do
    get "search", on: :collection
    # get '/autocomplete_song/:song', on: :collection, action: :autocomplete_song
    resources :post_comments, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]
  end
  get "users/:user_id/posts/:id", to: "posts#show", as: "post_show"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :subject, polymorphic: true
  belongs_to :user

  enum action: {
    request: 0,
    follow: 1,
    post_comment: 2
  }
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @notifications = current_user.notifications.order(created_at: :desc).page(params[:page]).per(20)
  end

  def read
    notification = current_user.notifications.find(params[:id])
    unless notification.read?
      notification.update(read: true)
    end
    redirect_to transition_path(notification)
  end

  def read_all
    current_user.notifications.update_all(read: true)
    redirect_to user_notifications_path(current_user.id)
  end
  # アクションタイプごとにリダイレクト先を指定
  def transition_path(notification)
    case notification.action
    when "request"
      # モーダルにリダイレクトするには？
      user_requests_path(notification.subject.requested_id)
    when "post_comment"
      post_path(notification.subject.post_id)
    when "follow"
      user_path(notification.subject.follower_id)
    else
      root_path
    end
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_follow.html.erb
<div class="d-flex">
  <%= image_tag notification.subject.follower.get_profile_image(75, 75), class: "rounded-circle mr-3" %>
  <div class="align-self-center">
    <%=  notification.subject.follower.name %> があなたをフォローしました
  </div>
  <div class="ml-auto align-self-end text-right">
    <%= l notification.created_at, format: :short %>
  </div>
</div>

app/views/notifications/_post_comment.html.erb
<div class="d-flex">
  <%= image_tag notification.subject.user.get_profile_image(75, 75), class: "rounded-circle mr-3" %>
  <div class="align-self-center">
    <%=  notification.subject.user.name %> があなたの投稿にコメントしました
  </div>
  <div class="ml-auto align-self-end text-right">
    <%= l notification.created_at, format: :short %>
  </div>
</div>

app/views/notifications/_request.html.erb
<div class="d-flex">
  <%= image_tag notification.subject.requester.get_profile_image(75, 75), class: "rounded-circle mr-3" %>
  <div class="align-self-center">
    <%=  notification.subject.requester.name %> からリクエストが届きました
  </div>
  <div class="ml-auto align-self-end text-right">
    <%= l notification.created_at, format: :short %>
  </div>
</div>

app/views/notifications/index.html.erb
<div class="container">

  <h4 class="d-inline-block ml-3">通知一覧</h4>
  <% if @notifications.present? %>
    <%= link_to "すべて既読にする", read_all_user_notifications_path(current_user.id), class: "btn btn-primary btn-sm mt-3 mb-4 ml-4", method: :patch, data: { confirm: "すべての通知を既読にしますか？" } %>
    <% @notifications.each do |notification| %>
      <%= link_to read_user_notification_path(current_user.id, notification), class: "text-dark text-decoration-none", method: :patch do %>
        <div class="border-bottom py-3 px-4 <%= 'bg-light text-secondary' if notification.read? %>">
          <%= render "#{notification.action}", notification: notification %>
        </div>
      <% end %>
    <% end %>
    <%= paginate @notifications %>
  <% else %>
    <p class="mt-3 ml-4">通知はありません</p>
  <% end %>
</div>