config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }
  devise_scope :user do
    get "/users/sign_out" => "users/sessions#destroy"
    post "users/guest_sign_in" => "users/sessions#guest_sign_in"
  end

  root to: "homes#top"
  get "about" => "homes#about"

  resources :users, except: [:new, :index, :destroy] do
    collection do
      get "confirm"
      patch "withdraw"
      get "search"
    end
    resources :requests, only: [:index, :create, :destroy]
    resource :follows, only: [:create, :destroy]
    resources :notifications, only: [:index] do
      patch :read, on: :member
      patch :read_all, on: :collection
    end
  end
  resources :posts, except: [:edit, :index, :show] do
    get "search", on: :collection
    # get '/autocomplete_song/:song', on: :collection, action: :autocomplete_song
    resources :post_comments, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]
  end
  get "users/:user_id/posts/:id", to: "posts#show", as: "post_show"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :post_comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  belongs_to :user
  belongs_to :song

  mount_uploader :audio, AudioUploader
  validates :audio, presence: { message: "を選択してください" }
  enum open_range: { public: 0, follow: 1, private: 2 }, _prefix: true  # 文末はエラー回避のため

  def self.search(search, word)
    # キーワード分割
    keywords = word&.split(/[[:blank:]]+/)&.select(&:present?)
    @songs = Song.all
    # キーワード検索から楽曲を特定
    if search == "perfect_match"
      @songs = @songs.where("artist_name like? OR song_name like?", "#{word}", "#{word}")
    elsif search == "forward_match"
      @songs = @songs.where("artist_name like? OR song_name like?", "#{word}%", "#{word}%")
    elsif search == "backward_match"
      @songs = @songs.where("artist_name like? OR song_name like?", "%#{word}", "%#{word}")
    elsif search == "partial_match"
      keywords.each do |keyword|
        @songs = @songs.where("artist_name like? OR song_name like?", "%#{keyword}%", "%#{keyword}%")
      end
    end
    # 曲のidに合致する投稿を抽出
    Post.where(song_id: @songs.ids).order("created_at DESC")
  end

  # # サジェスト用の前方一致検索
  # scope :by_song_like, -> (song) { where('song LIKE :value', { value: "#{song}%"}) }

  # 同じ歌手の投稿から自分の投稿、表示中の投稿、いいね済を除外しいいねが多い順に並べる
  def self.post_recommend(user, pos, artist_name)
    songs = Song.where(artist_name: artist_name).pluck(:id)
    like_posts = user.likes.pluck(:post_id)
    @posts = Post.where(song_id: songs).where.not(user_id: user.id).where.not(id: pos.id).where.not(id: like_posts).limit(5).sort { |a, b| b.likes.count <=> a.likes.count }
  end

  def self.post_create(artist_name, song_name, pos)
    # 曲が存在しているかのチェック
    # エラーメッセージにsongの情報を渡すために$を
    $song = Song.find_by(artist_name: artist_name, song_name: song_name)
    if $song.present?
      pos.song_id = $song.id
    else
      $song = Song.create(artist_name: artist_name, song_name: song_name)
      pos.song_id = $song.id
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:search]
  before_action :guest_check, only: [:new]
  before_action :is_matching_login_user, only: [:edit, :update, :destroy]
  before_action :open_range_check, only: [:show]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    Post.post_create(params[:post][:artist_name], params[:post][:song_name], @post)
    if @post.save
      redirect_to user_path(current_user.id), success: "楽曲を投稿しました。"
    else
      # PostモデルのエラーからSongモデルのアソシエーションのエラーを削除
      @post.errors.delete(:song)
      render "new"
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to user_path(current_user.id), success: "投稿曲の設定を変更しました。"
    else
      render "users/show"
    end
  end

  def destroy
    pos = Post.find(params[:id])
    pos.destroy
    redirect_to user_path(current_user.id), success: "投稿を削除しました。"
  end

  def show
    @post = Post.find(params[:id])
    @posts = Post.post_recommend(current_user, @post, @post.song.artist_name)
    @post_comment = PostComment.new
    @post_comments = @post.post_comments.all
  end

  def search
    @posts = Post.search(params[:search], params[:word])
    @post_search_result = @posts.page(params[:page]).per(10)
    if @posts.count != 0
      flash.now[:primary] = "#{@posts.count}件の投稿が見つかりました。"
    else
      flash.now[:danger] = "投稿が見つかりませんでした。"
    end
  end

  # def autocomplete_song
  #   # params[:company]の値でUser.companyを前方一致検索、company列だけ取り出し、nilと空文字を取り除いた配列
  #   songs = Song.by_song_like(autocomplete_params[:song_name]).pluck(:song_name).reject(&:blank?)
  #   render json: songs
  #   # レスポンスの例: ["てすと１会社","てすと２会社","てすと３会社"]
  # end

  private
    def post_params
      params.require(:post).permit(:audio, :open_range, :poster_comment)
    end

    # def autocomplete_params
    #     params.permit(:song_name)
    # end

    def is_matching_login_user
      pos = Post.find(params[:id])
      unless pos.user_id == current_user.id
        redirect_to user_path(current_user.id)
      end
    end
    
    def open_range_check
      pos = Post.find(params[:id])
      pos_user = User.find(params[:user_id])
      if pos_user != current_user
        if pos.open_range == "follow" && User.mutual_follows?(pos_user, current_user) == false 
          redirect_to user_path(pos_user.id), flash: { primary: "この投稿曲は相互フォロー限定です。"}
        elsif pos.open_range == "private"
          redirect_to user_path(pos_user.id), flash: { primary: "この投稿曲は非公開です。" }
        end
      end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_error_messages.html.erb
<% if model.errors.any? || model2&.errors&.any? %>
  <div class="alert alert-danger">
    <ul class="mb-0 list-unstyled">
      <% model.errors&.full_messages&.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      <% model2&.errors&.full_messages&.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/posts/_posts_list.html.erb
<% posts.each do |pos| %>
  <div class="card-wrapper">
    <%= link_to post_show_path(pos.user_id, pos.id), class: "text-dark text-decoration-none" do %>
      <div class="shadow bg-light rounded p-4 pb-5 mt-3" style="min-height: 115px;">
        <div class="row mx-0 justify-content-between">
          <div class="h6">
            <span class="font-weight-bold"><%= pos.song&.song_name %> / <%= pos.song&.artist_name %></span>
          </div>
          <div><%= pos.created_at.strftime('%Y/%m/%d') %>投稿</div>
        </div>
        <% if action_name == "search" %>
          <div class="mb-3"><%= pos.user.name %> さん</div>
        <% end %>
        <% if pos.poster_comment.present? %>
          <div class="my-1 text-break mb-3 d-flex align-items-start"><span class="mr-2 p-1 text-white bg-secondary rounded text-nowrap" style="font-size: 11px;">投稿者コメント</span><%= pos.poster_comment %></div>
        <% end %>
      </div>
    <% end %>
    <!--ユーザーの判定-->
    <% if params[:id] == current_user&.id.to_s %>
      <div class="favorite-link">
        <a href="#" data-toggle="modal" data-target="#exampleModal<%= pos.id %>" ><span class="pr-2"><%= icon("fas", "heart") %></span><%= pos.likes.count %></a>
        <span class="pl-3"><span class="pr-2"><%= icon("far", "comment") %></span><%= pos.post_comments.count %></span>
      </div>
      <div class="config-link mr-2">
        <span class="align-middle" style="font-size: 13px;"><%= pos.open_range_i18n %></span>
        <a href="#" data-toggle="modal" data-target="#configModal<%= pos.id %>", class="btn btn-sm btn-outline-primary ml-2">編集</a>
        <%= link_to "削除", post_path(pos.id), method: :delete, class: "btn btn-sm btn-outline-danger ml-1", data: {confirm: "本当に削除しますか？"} %>
      </div>
      <!--モーダル-->
      <div class="modal" id="exampleModal<%= pos.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">いいね履歴</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <% pos.likes.each do |like| %>
                <div class="ml-4 mb-2">
                  <%= link_to like.user.name, user_path(like.user_id) %> さん
                  <span class="ml-3"><%= like.created_at.strftime('%Y/%m/%d') %></span>
                </div>
              <% end %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
            </div>
          </div>
        </div>
      </div>
      <div class="modal" id="configModal<%= pos.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">投稿曲の編集</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body mx-3">
              <%= form_with model: pos, url: post_path(pos.id) do |f| %>
                <div class="form-group">
                  <%= f.label :poster_comment, "コメント", class: "col-form-label" %>
                  <%= f.text_area :poster_comment, class: "form-control" %>
                </div>
                <div class="form-group">
                  <%= f.label :open_range, "公開範囲", class: "col-form-label" %>
                  <%= f.select :open_range, Post.open_ranges.keys.map {|k| [I18n.t("enums.post.open_range.#{k}"), k]}, {},{ class: "form-control"} %>
                </div>
                <%= f.submit "変更", class: "btn btn-primary my-3" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% else %>
      <div class="favorite-link">
        <span class="pr-2"><%= icon("fas", "heart") %></span><%= pos.likes.count %><span class="pl-4"><span class="pr-2"><%= icon("far", "comment") %></span><%= pos.post_comments.count %></span>
      </div>
    <% end %>
  </div>
<% end %>

<% if action_name == "search" %>
  <div class="mt-5 text-center"><%= paginate posts %></div>
<% end %>

app/views/posts/new.html.erb
<div class="container">
  <h3 class="mt-4">新規投稿</h3>
  <p class="alert alert-warning mt-4"><strong>注意事項</strong><br>
  投稿には必ず利用許諾のある音源を使用してください。<br>
  カラオケ音源を無断で使用する事は著作権で禁じられています。<br>
  著作権違反の投稿はを管理者が見つけ次第削除いたします。</p>

  <%= form_with model: @post, url: posts_path, class: "mt-4" do |f| %>
    <%= render 'error_messages', model: @post, model2: $song, class: "mb-3" %>
    <div class="form-group row ml-3">
      <%= f.label :audio, "音声ファイル", class: "col-md-2 col-3 col-form-label" %>
      <%= f.file_field :audio, accept: "audio/*", class: "form-control-file col-md-6 col-9  my-auto" %>
    </div>

    <div class="form-group row ml-3">
      <%= f.label :artist_name, "歌手名", class: "col-md-2 col-3 col-form-label" %>
      <%= f.text_field :artist_name, class: "form-control col-md-6 col-8" %>
    </div>

    <div class="form-group row ml-3">
      <%= f.label :song_name, "曲名", class: "col-md-2 col-3 col-form-label" %>
      <%= f.text_field :song_name, class: "form-control col-md-6 col-8" %>
    </div>
    
    <div class="form-group row ml-3">
      <%= f.label :open_range, "公開範囲", class: "col-md-2 col-3 col-form-label" %>
      <%= f.select :open_range, Post.open_ranges.keys.map {|k| [I18n.t("enums.post.open_range.#{k}"), k]}, {},{ class: "form-control col-md-6 col-8"} %>
    </div>

    <div class="form-group row ml-3">
      <%= f.label :poster_comment, "コメント", class: "col-md-2 col-3 col-form-label" %>
      <%= f.text_area :poster_comment, class: "form-control col-md-6 col-8" %>
    </div>

    <div class="d-flex col-md-5 col-12 mt-4">
      <%= f.submit "投稿する", class: "btn btn-success ml-md-3 px-md-5 btn-block" %>
    </div>
  <% end %>
</div>

app/views/posts/search.html.erb
<div class="container col-lg-7 mx-auto">
  <h4 class="mb-3">投稿検索</h4>
  <p style="font-size: 14px;">部分一致のみ、スペース区切りでのAND検索ができます。</p>
  <%= form_tag(search_posts_path, method: :get, class: "form-group form-inline mt-4") do %>
    <%= text_field_tag :word, params[:word], placeholder: "歌手名／曲名を入力", class: "form-control mr-sm-3 mb-2 mb-sm-0", size: 30 %>
    <%= select_tag :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]], { selected: params[:search] }), class: "form-control mr-sm-3 mb-2 mb-sm-0"  %>
    <%= submit_tag "検索", class: "btn btn-primary" %>
  <% end %>
  <%= render 'shared/flash_message' %>
  <%= render 'posts_list', posts: @post_search_result %>
</div>

app/views/posts/show.html.erb
<div class="container d-lg-flex">

  <div class="col-lg-7 col-12">
    <div class="row m-0 align-items-center mt-3 px-0">
      <div class="mr-lg-4 mr-2 p-3 ">
        <div><%= image_tag @post.user.get_profile_image(100,100), class: "rounded-circle" %></div>
        <div class="mt-2 text-center"><%= link_to @post.user.name, user_path(@post.user_id) %> さん</div>
      </div>
      <audio src= "<%= "#{@post.audio}" %>"controls="" class=""></audio>
    </div>

    <div class="rounded shadow bg-light border-dark p-4 mt-4">
      <div class="row m-0">
        <div class="mr-5 h5">
          <%= @post.song.song_name %> / <%= @post.song.artist_name %>
        </div>
        <div>
          <%= @post.created_at.strftime('%Y/%m/%d') %> 投稿
        </div>
      </div>

      <div class="mt-3 row">
        <% if @post.poster_comment.present? %>
          <div class="col-10"><span class="mr-2 p-1 text-white bg-secondary rounded" style="font-size: 11px;">投稿者コメント</span><%= @post.poster_comment %></div>
        <% end %>
        <div class="mt-2 col-2 px-0" id="likes">
          <% if current_user == @post.user || current_user.id == 1 %>
            <span class="btn btn-outline-dark disabled"><span class="pr-2"><%= icon("fas", "heart") %></span><%= @post.likes.count %></span>
          <% else %>
            <%= render "likes/like" %>
          <% end %>
        </div>
      </div>
    </div>


    <div class="mt-5" id="comments_list">
      <%= render 'post_comments/comments_list' %>
    </div>
    <% unless current_user.id == 1 %>
      <div class="mt-4">
        <%= render 'post_comments/form' %>
      </div>
    <% end %>
  </div>

  <div class="col-lg-4 offset-lg-1 col-12">
    <h6 class="mb-4 mb-lg-4 mt-5 mt-lg-4 px-3 py-2  border-bottom border-primary shadow"><%= @post.song.artist_name %>のおすすめ投稿</h6>
    <% unless @posts.empty? %>
      <% @posts.each do |pos| %>
        <div class="border rounded p-4 mt-2 position-relative">
          <div class="h6">
            <%= link_to post_path(pos.id), class: "text-dark text-decoration-none font-weight-bold stretched-link" do %>
              <%= pos.song.song_name %> /
              <%= pos.song.artist_name %>
            <% end %>
          </div>
          <div class="mb-2"><%= pos.created_at.strftime('%Y/%m/%d') %>投稿</div>
          <div>
            <%= pos.user.name %> さん
            <span class="pl-4"><span class="pr-2"><%= icon("fas", "heart") %></span><%= pos.likes.count %></span><span class="pl-4"><span class="pr-2"><%= icon("far", "comment") %></span><%= pos.post_comments.count %></span>
          </div>
        </div>
      <% end %>
    <% else %>
      <span class="pl-3">あなたへのおすすめはありません。</span>
    <% end %>
  </div>




</div>