config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }
  devise_scope :user do
    get "/users/sign_out" => "users/sessions#destroy"
    post "users/guest_sign_in" => "users/sessions#guest_sign_in"
  end

  root to: "homes#top"
  get "about" => "homes#about"

  resources :users, except: [:new, :index, :destroy] do
    collection do
      get "confirm"
      patch "withdraw"
      get "search"
    end
    resources :requests, only: [:index, :create, :destroy]
    resource :follows, only: [:create, :destroy]
    resources :notifications, only: [:index] do
      patch :read, on: :member
      patch :read_all, on: :collection
    end
  end
  resources :posts, except: [:edit, :index, :show] do
    get "search", on: :collection
    # get '/autocomplete_song/:song', on: :collection, action: :autocomplete_song
    resources :post_comments, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]
  end
  get "users/:user_id/posts/:id", to: "posts#show", as: "post_show"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ぽすカラ</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="body-wrapper">
      <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-info">
          <div class="container">
            <a class="navbar-brand p-3 text-white" href="/"><span class="h3 logo">ぽす<%= icon('fas', 'music') %> カラ</span></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse flex-grow-0" id="navbarNavDropdown">
              <ul class="navbar-nav">
              <% if user_signed_in? %>
                <li class="nav-item"><%= link_to 'マイページ', user_path(current_user.id), class: "nav-link text-white" %></li>
                <li class="nav-item">
                  <%= link_to user_notifications_path(current_user.id), class: "nav-link text-white" do %>
                    <span class="position-relative">通知一覧<%= render 'shared/unread_badge' %></span>
                  <% end %>
                </li>
                <li class="nav-item"><%= link_to 'ユーザー検索', search_users_path, class: "nav-link text-white" %></li>
                <li class="nav-item"><%= link_to '投稿を探す', search_posts_path, class: "nav-link text-white" %></li>
                <li class="nav-item"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "nav-link text-white" %></li>
              <% else %>
                <li class="nav-item pr-2"><%= link_to '新規登録', new_user_registration_path, class: "nav-link text-white" %></li>
                <li class="nav-item pr-2"><%= link_to 'ログイン', new_user_session_path, class: "nav-link text-white" %></li>
                <li class="nav-item pr-2"><%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: :post, class: "nav-link text-white" %></ %></li>
                <li class="nav-item pr-2"><%= link_to '投稿を探す', search_posts_path, class: "nav-link text-white" %></li>
              <% end %>
              </ul>
              <div class="ml-lg-4 my-3 my-lg-0">
                <!--検索フォーム-->
                <%= form_tag(search_posts_path, method: :get, class: "form-inline") do %>
                  <%= text_field_tag :word, "", placeholder: "歌手名／曲名を入力", class: "form-control-sm mr-2" %>
                  <%= hidden_field_tag :search, "forward_match" %>
                  <%= submit_tag "検索", class: "btn-sm btn-primary header-search" %>
                <% end %>
              </div>
            </div>
          </div>
        </nav>
      </header>
      <main>
        <%= yield %>
      </main>
      <footer class="text-center mt-5 bg-info">
        <p class=" py-5 mb-0 text-white">Copyright © Hiroki Kondo All Rights Reserved.</p>
      </footer>
    </div>
  </body>
</html>